config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :ratings
  resources :over_categories
  resources :category_groups
  root to: 'products#index'
  
  devise_for :users
  
  resources :messages
  resources :rooms
  resources :products
  resources :categories
  resources :categories, only: [:index] 
  resources :order_items, path: '/cart/items'


  get '/cart', to: 'order_items#index', as: 'payment_method'
  get 'rooms/:id',to: 'application#show'
  get 'categories/:id/products/new', to: 'products#new', as: 'new_category_product'
  get 'success', to: "checkout#success"
  get 'cancel', to: "checkout#cancel"
  get '/history', to: "transactions#index"
  get '/transactions', to: "transactions#admin_index", as: 'all_transactions'
  get '/transaction/:id/items', to: "transaction_items#index", as: 'transaction_items'
  get '/transaction/:id/details', to: "transaction_items#admin_index", as: 'admin_transaction_items'
  get '/invoice/:id', to: "transactions#invoice", as: "invoice"
  get '/categories/:id/products', to: "categories#index", as: 'category_products'
  get '/sub_category/new/:id', to: "category_groups#new", as: 'new_sub_category'
  get '/variant/new/:id', to: "categories#new", as: 'new_variant'
  get :search, controller: :products
  post 'checkout/create', to: "checkout#create"
  post 'delivery/create', to: "transactions#create", as: 'on_delivery'
  delete '/cart/clear', to: 'order_items#clear'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'
  delete '/categories/:id', to: 'categories#destroy', as: 'delete_category'

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :destroy
    belongs_to :category_group
end

app/models/category_group.rb
class CategoryGroup < ApplicationRecord
    has_many :categories, dependent: :destroy
    belongs_to :over_category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items, class_name:'OrderItem', dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order        
    belongs_to :product
end

app/models/over_category.rb
class OverCategory < ApplicationRecord
  has_many :subcategories, class_name: 'CategoryGroup', dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord

    validates :title, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0.01}
    validates :description, presence: true

    belongs_to :category
    has_one_attached :image, dependent: :destroy
    has_one_attached :ad, dependent: :destroy
    has_many :transaction_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    has_many :ratings, dependent: :destroy
    has_many :comments, dependent: :destroy
    include Rails.application.routes.url_helpers

    scope :filter_by_category, -> (category_id) {where category_id: category_id}
    scope :filter_by_rating, -> (rating) {where "rating >= ?",rating }
    scope :filter_by_min_price, -> (min_price) {where "price >= ?",min_price }
    scope :filter_by_max_price, -> (max_price) {where "price <= ?",max_price }

    def thumbnail 
        return self.image.variant(resize: '300x300!').processed
    end
    
    def image_url
        rails_blob_path(self.image, disposition: "attachment", only_path: true)
    end

    def ad_url
        rails_blob_path(self.ad, disposition: "attachment", only_path: true)
    end

    def show_thumbnail
        return self.image.variant(resize: '550x550!').processed 
    end

    def cart_thumbnail
        return self.image.variant(resize: '100x100!').processed   
    end


    def to_s
        title
    end
    
    after_create do 
        product = Stripe::Product.create(name: title , description: description, images: ["https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/32/7041/1.jpg?0874"])
        price = Stripe::Price.create(product: product, unit_amount: self.price.to_i*100, currency: "usd")
        update(stripe_product_id: product.id, stripe_price_id: price.id)
    end

    after_update :create_and_assign_new_stripe_price, if: :saved_change_to_price?
    def create_and_assign_new_stripe_price
        price = Stripe::Price.create(product: self.stripe_product_id, unit_amount: self.price.to_i*100, currency: "usd")
        update(stripe_price_id: price.id)
    end

    
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    belongs_to :user
    
end

app/models/shopping_cart.rb
class ShoppingCart

  def initialize(token:)
    @token = token
  end
  
  def order
    @order ||= Order.find_or_create_by(token: @token) do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)

    order_item = order.items.find_or_initialize_by(product_id: product_id)
    order_item.price = product.price
    order_item.quantity = order_item.quantity.to_i + quantity.to_i
    order_item.save
  end

  def remove_item(id:)
    order.items.destroy(id)
  end

  def remove_items
    order.items.destroy_all
  end

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  has_many :transaction_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_one :room, dependent: :destroy
  has_one_attached :avatar,dependent: :destroy
  has_one :ratings
  has_many :comments
  include Rails.application.routes.url_helpers


  def to_s
    email
  end

  after_create do 
    customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: customer.id)
  end
  def image_url
    rails_blob_path(self.avatar, disposition: "attachment", only_path: true)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/shared/_ads_slider.html.erb
<style>
    #carousel-container {
        width: 1200px;
        height: 235px;
        position: relative;
        margin: 50px auto 0;
    }

    #carousel-container > div:first-child {
        overflow: hidden;
        max-width: 100%;
        margin: 0;
    }

    #carousel {
        position: relative;
        width: 1200px;
        height: 235px;
        padding: 0;
        margin: 0;
    }

    .animate{
        -webkit-transition-duration: 1.3s;
        -moz-transition-duration: 1.3s;
        -o-transition-duration: 1.3s;
        transition-duration: 1.3s;
        -webkit-transition-property: -webkit-transform;
        -moz-transition-property: -moz-transform;
        -o-transition-property: -o-transform;
        transition-property: transform;
    }

    .slide {
        list-style: none;
        position: relative;
        float: left;
        transform: translateX(-500px)
    }

    #controls{
        position: absolute;
        width: 1200px;
        top: calc( 50% - 25px);
        margin: 0 ;
    }

    #controls span {
        width: 50px;
        cursor: pointer;
        opacity: 0.4;
    }

    #controls span:hover {
        opacity: 1;
    }

    #prev {
        float: left;
    }

    #next {
        float: right;
    }
</style>
<div id="carousel-container">
    <div>
        <ul id="carousel" class="animate">
            <% products.each do |product| %>
                <% if product.ad.attached? && product.show_ad=="true" %>
                    <li class="slide animate">
                        <%= link_to product_path(product.id) do %>
                            <%= image_tag prod_ad(product), class:"w-full transition duration-700 ease-in-out group-hover:opacity-60" %>
                        <%end%>
                    </li>
                <% end %>
            <% end %>
        </ul> 
    </div>
    <div id="controls">
        <span id="prev"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1014830/prev.png"></span>
        <span id="next"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1014830/next.png"></span>
    </div>
</div>
<script>
    var index = 0,
        amount = 0,
        currTransl = [],
        translationComplete = true,
        moveOffset = 0;
    var timer;
    var transitionCompleted = function(){
        translationComplete = true;
    }

    document.addEventListener("turbolinks:load", function(event) 
    {
        var carousel = document.getElementById('carousel');

        amount = document.getElementsByClassName("slide").length;
        moveOffset = parseInt(window.getComputedStyle(document.getElementById('carousel-container')).width, 10);
        document.getElementById('carousel').style.width = (amount * moveOffset) + 'px';
        for(var i = 0; i < amount; i++)
        {
            currTransl[i] = -moveOffset;
            document.getElementsByClassName("slide")[i].addEventListener("transitionend", transitionCompleted, true);                    
            document.getElementsByClassName("slide")[i].addEventListener("webkitTransitionEnd", transitionCompleted, true);                    
            document.getElementsByClassName("slide")[i].addEventListener("oTransitionEnd", transitionCompleted, true);                    
            document.getElementsByClassName("slide")[i].addEventListener("MSTransitionEnd", transitionCompleted, true);                  
        }
        document.getElementById('carousel').insertBefore(document.getElementById('carousel').children[amount -1], document.getElementById('carousel').children[0])
        document.getElementById('prev').addEventListener('click', prev, true);
        document.getElementById('next').addEventListener('click', next, true);
        next();
    });

    function prev()
    {
        if (translationComplete === true)
        {
            translationComplete = false;
            index--;
            if (index == -1)
            {
                index = amount-1;
            }
            var outerIndex = (index) % amount;
            for (var i = 0; i < amount; i++)
            {
                var slide = document.getElementsByClassName("slide")[i];    
                slide.style.opacity = '1';    
                slide.style.transform = 'translateX('+(currTransl[i]+moveOffset)+'px)';
                currTransl[i] = currTransl[i]+moveOffset;
            }
            var outerSlide = document.getElementsByClassName("slide")[outerIndex];
            outerSlide.style.transform = 'translateX('+(currTransl[outerIndex]-(moveOffset*amount))+'px)';
            outerSlide.style.opacity = '0';
            currTransl[outerIndex] = currTransl[outerIndex]-moveOffset*(amount);
        }
    }

    function next()
    {
        if (translationComplete === true)
        {
            translationComplete = false;
            var outerIndex = (index) % amount;
            index++;
            for(var i = 0; i < amount; i++)
            {
                var slide = document.getElementsByClassName("slide")[i];    
                slide.style.opacity = '1';    
                slide.style.transform = 'translateX('+(currTransl[i]-moveOffset)+'px)';
                currTransl[i] = currTransl[i]-moveOffset;
            }
            var outerSlide = document.getElementsByClassName("slide")[outerIndex];
            outerSlide.style.transform = 'translateX('+(currTransl[outerIndex]+(moveOffset*amount))+'px)';
            outerSlide.style.opacity = '0';
            currTransl[outerIndex] = currTransl[outerIndex]+moveOffset*(amount);
        };
        clearTimeout(timer);
        timer = setTimeout(next,6000)
    }
    
</script>

app/views/shared/_cart.html.erb
<div class="mx-2 h-full" >
    <% total = 0 %>
    <% items.each do |item| %>
        <%  total = total.to_i + (item.quantity.to_i * item.price)%>
        <div class="flex justify-between mt-6">
            <div class="flex"> 
                <% if item && item.product.image.attached?%>
                    <%= image_tag item.product.image_url, class:"h-20 w-20 object-cover rounded" %>
                <% else %>
                    <img class="h-20 w-20 object-cover rounded" src="https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80" alt="">
                <% end %>
                <div class="mx-3">
                    <h3 class="text-sm text-gray-600">
                        <%= item.product.title %>
                    </h3>
                    <div class="flex items-center mt-2" >
                        <button class="text-gray-500 focus:outline-none focus:text-gray-600">
                            <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                        </button>
                        <span class="text-gray-700 mx-2">
                            <%= item.quantity %>
                        </span>
                        <button class="text-gray-500 focus:outline-none focus:text-gray-600">
                            <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                        </button>
                    </div>
                </div>
            </div>
            <span class="text-gray-600">
                <%= number_to_currency item.price*item.quantity %>
                <%= link_to t("Remove"), order_item_path(item), method: :delete, class:"ml-3 flex items-center px-3 py-2 bg-blue-600 text-white text-sm uppercase font-medium rounded hover:bg-blue-500 focus:outline-none focus:bg-blue-500" %>
            </span>
        </div>
    <% end %>
    <span class="text-gray-600">
        <h3 class="text-sm text-gray-600 mt-5 ">Total: </h3><%= number_to_currency total %>
    </span>
    <div class="flex justify-bewtween " >
        <%= link_to payment_method_path, method: :get, class:"mx-2 flex items-center justify-center mt-4 px-2 py-2 bg-blue-600 text-white text-sm uppercase font-medium rounded hover:bg-blue-500 focus:outline-none focus:bg-blue-500", data: {disable_with: t("Validating")} do %>
            <span><%= t("Checkout") %></span>
            <svg class="h-5 w-5 mx-2" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
        <% end %>
        <%= button_to cart_clear_path, method: :delete, remote: true, class:"right mx-2 inline flex items-center justify-center mt-4 px-2 py-2 bg-blue-600 text-white text-sm uppercase font-medium rounded hover:bg-blue-500 focus:outline-none focus:bg-blue-500" do %>
            <span><%= t("Clear Cart") %></span>
        <% end %>
    </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="text-center py-3 px-5 mb-4 bg-green-100 text-green-900 text-sm rounded-md border border-green-200" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>


<% if flash[:alert] %>
    <div class="text-center py-3 px-5 mb-4 bg-red-100 text-red-900 text-sm rounded-md border border-red-200" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>