config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :ratings
  resources :over_categories
  resources :category_groups
  root to: 'products#index'
  
  devise_for :users
  
  resources :messages
  resources :rooms
  resources :products
  resources :categories
  resources :categories, only: [:index] 
  resources :order_items, path: '/cart/items'


  get '/cart', to: 'order_items#index', as: 'payment_method'
  get 'rooms/:id',to: 'application#show'
  get 'categories/:id/products/new', to: 'products#new', as: 'new_category_product'
  get 'success', to: "checkout#success"
  get 'cancel', to: "checkout#cancel"
  get '/history', to: "transactions#index"
  get '/transactions', to: "transactions#admin_index", as: 'all_transactions'
  get '/transaction/:id/items', to: "transaction_items#index", as: 'transaction_items'
  get '/transaction/:id/details', to: "transaction_items#admin_index", as: 'admin_transaction_items'
  get '/invoice/:id', to: "transactions#invoice", as: "invoice"
  get '/categories/:id/products', to: "categories#index", as: 'category_products'
  get '/sub_category/new/:id', to: "category_groups#new", as: 'new_sub_category'
  get '/variant/new/:id', to: "categories#new", as: 'new_variant'
  get :search, controller: :products
  post 'checkout/create', to: "checkout#create"
  post 'delivery/create', to: "transactions#create", as: 'on_delivery'
  delete '/cart/clear', to: 'order_items#clear'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'
  delete '/categories/:id', to: 'categories#destroy', as: 'delete_category'

end

app/models/over_category.rb
class OverCategory < ApplicationRecord
  has_many :subcategories, class_name: 'CategoryGroup', dependent: :destroy
end

app/controllers/over_categories_controller.rb
class OverCategoriesController < ApplicationController
  before_action :set_over_category, only: %i[ show edit update destroy ]

  # GET /over_categories or /over_categories.json
  def index
    @over_categories = OverCategory.all
  end

  # GET /over_categories/1 or /over_categories/1.json
  def show
    @category_groups = CategoryGroup.where(over_category_id: params[:id])
  end

  # GET /over_categories/new
  def new
    @over_category = OverCategory.new
  end

  # GET /over_categories/1/edit
  def edit
  end

  # POST /over_categories or /over_categories.json
  def create
    @over_category = OverCategory.new(over_category_params)

    respond_to do |format|
      if @over_category.save
        format.html { redirect_to @over_category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @over_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @over_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /over_categories/1 or /over_categories/1.json
  def update
    respond_to do |format|
      if @over_category.update(over_category_params)
        format.html { redirect_to @over_category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @over_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @over_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /over_categories/1 or /over_categories/1.json
  def destroy
    @over_category.destroy
    respond_to do |format|
      format.html { redirect_to over_categories_url, notice: "Over category was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_over_category
      @over_category = OverCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def over_category_params
      params.require(:over_category).permit(:name)
    end
end

app/helpers/over_categories_helper.rb
module OverCategoriesHelper
end

app/views/over_categories/_form.html.erb
<div class="w-screen flex items-center justify-center py-8 overflow-auto" >
    <div class="border rounded-lg border-gray-300 shadow-xl text-gray-900 bg-gray-200 w-6/12 max-h-max">
        <div class="max-w-7xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
            <div class="mt-5 md:mt-0 md:col-span-2">
                <%= form_with(model: over_category)  do |f|%>
                    <div class="shadow sm:rounded-md sm:overflow-hidden">
                        <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                            <div class="grid grid-cols-3 gap-6">
                                <div class="col-span-6 sm:col-span-3">
                                    <%= f.label t("Name"), class:"block text-sm font-medium text-gray-700 mb-5" %> 
                                    <%= f.text_field :name , class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-100 sec p-3 h-30  border border-gray-300 outline-none " %>
                                </div>
                            </div>
                        </div>
                        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <%= f.submit t("Save Category"), class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-500 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500", data: {disable_with: "Validating ..."}%>
                        </div>
                    </div>
                <%end%>
            </div>
            <%= link_to t('Back'), over_categories_path, class:"mt-4 text-center flex w-20 justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
        </div>
    </div>
</div>

app/views/over_categories/edit.html.erb
<div class="flex justify-center" >
    <h1 class="mt-4 ml-4 text-xl" ><%= t("Edit Category") %></h1>
</div>

<%= render 'form', over_category: @over_category%>

app/views/over_categories/index.html.erb
<div class="mt-5 pb-5 w-screen flex items-center justify-center min-h-max" >
  <div class="border rounded-lg border-gray-300 shadow-xl text-gray-900 bg-gray-200 max-w-max max-h-max">
    <div class="p-4 flex justify-center">
      <h1 class="text-3xl">
        <%= t("Categories")%> 
      </h1>
    </div>
    <div class="px-3 py-4 flex justify-center">
        <table class="w-96 text-md bg-white shadow-md rounded mb-4">
          <% @over_categories.each do |over_category| %>
            <tr class="border-b hover:bg-orange-100 bg-gray-100">
              <td class="p-3 px-5">
                <%= link_to over_category, class:"bg-transparent" do %>
                  <%= t(over_category.name) %>
                <% end %>
              </td>
              <td class="p-3 px-5 flex justify-end" >
                <%= link_to t('Edit'), edit_over_category_path(over_category), class:"mr-3 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
                <%= link_to t('Delete'), over_category, method: :delete, data: { confirm: "Deleteing this category will delete all it's sub-categories, proceed anyway ?" }, class:"text-sm bg-red-500 hover:bg-red-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
              </td>
            </tr>
          <% end %>
          <tr class="border-b hover:bg-orange-100 bg-gray-100">
            <td  colspan="2" class="p-3" >
              <%= link_to t('Add Category'), new_over_category_path, class:"w-full text-center flex justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
            </td>
          </tr>
        </table>
    </div>
  </div>
</div>

app/views/over_categories/new.html.erb
<div class="flex justify-center" >
    <h1 class="mt-4 ml-4 text-xl" ><%= t("New Category") %></h1>
</div>

<%= render 'form', over_category: @over_category %>

app/views/over_categories/show.html.erb
<div class="my-5 pb-5 w-screen flex items-center justify-center min-h-max" >
  <div class="border rounded-lg border-gray-300 shadow-xl text-gray-900 bg-gray-200 max-w-max max-h-max">
    <div class="text-gray-900 bg-gray-200">
      <div class="p-4 flex justify-center">
          <h1 class="text-3xl">
            <%= @over_category.name %> <%= t("Sub-Categories") %>
          </h1>
      </div>
      <div class="px-3 py-4 flex justify-center">
          <table class="w-96 text-md bg-white shadow-md rounded mb-4">
            <% @category_groups.each do |category_group| %>
              <tr class="border-b hover:bg-orange-100 bg-gray-100">
                <td class="p-3 px-5">
                  <%= link_to category_group, class:"bg-transparent" do %>
                    <%= t(category_group.name) %>
                  <% end %>
                </td>
                <td class="p-3 px-5 flex justify-end" >
                  <%= link_to t('Edit'), edit_category_group_path(category_group), class:"mr-3 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
                  <%= link_to t('Delete'), category_group, method: :delete, data: { confirm: "Deleteing this sub-category will delete all it's variants, proceed anyway ?" }, class:"text-sm bg-red-500 hover:bg-red-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
                </td>
              </tr>
            <% end %>
            <tr class="border-b hover:bg-orange-100 bg-gray-100">
              <td  colspan="2" class="p-3" >
                <%= link_to t('Add Sub-Category'), new_sub_category_path(@over_category), class:"w-full text-center flex justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
              </td>
            </tr>
          </table>
      </div>
      <%= link_to t('Back'), over_categories_path, class:"mb-2 text-center flex w-20 justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </div>
</div>