config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :ratings
  resources :over_categories
  resources :category_groups
  root to: 'products#index'
  
  devise_for :users
  
  resources :messages
  resources :rooms
  resources :products
  resources :categories
  resources :categories, only: [:index] 
  resources :order_items, path: '/cart/items'


  get '/cart', to: 'order_items#index', as: 'payment_method'
  get 'rooms/:id',to: 'application#show'
  get 'categories/:id/products/new', to: 'products#new', as: 'new_category_product'
  get 'success', to: "checkout#success"
  get 'cancel', to: "checkout#cancel"
  get '/history', to: "transactions#index"
  get '/transactions', to: "transactions#admin_index", as: 'all_transactions'
  get '/transaction/:id/items', to: "transaction_items#index", as: 'transaction_items'
  get '/transaction/:id/details', to: "transaction_items#admin_index", as: 'admin_transaction_items'
  get '/invoice/:id', to: "transactions#invoice", as: "invoice"
  get '/categories/:id/products', to: "categories#index", as: 'category_products'
  get '/sub_category/new/:id', to: "category_groups#new", as: 'new_sub_category'
  get '/variant/new/:id', to: "categories#new", as: 'new_variant'
  get :search, controller: :products
  post 'checkout/create', to: "checkout#create"
  post 'delivery/create', to: "transactions#create", as: 'on_delivery'
  delete '/cart/clear', to: 'order_items#clear'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'
  delete '/categories/:id', to: 'categories#destroy', as: 'delete_category'

end

app/models/category_group.rb
class CategoryGroup < ApplicationRecord
    has_many :categories, dependent: :destroy
    belongs_to :over_category
end

app/controllers/category_groups_controller.rb
class CategoryGroupsController < ApplicationController
  before_action :set_category_group, only: %i[ show edit update destroy ]

  # GET /category_groups or /category_groups.json
  def index
    @category_groups = CategoryGroup.all
  end

  # GET /category_groups/1 or /category_groups/1.json
  def show
    @categories = Category.where(category_group_id: params[:id])
  end

  # GET /category_groups/new
  def new
    @category_group = CategoryGroup.new
  end

  # GET /category_groups/1/edit
  def edit
  end

  # POST /category_groups or /category_groups.json
  def create
    @category_group = CategoryGroup.new(category_group_params)

    respond_to do |format|
      if @category_group.save
        format.html { redirect_to @category_group, notice: "Sub-Category was successfully created." }
        format.json { render :show, status: :created, location: @category_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_groups/1 or /category_groups/1.json
  def update
    respond_to do |format|
      if @category_group.update(category_group_params)
        format.html { redirect_to @category_group, notice: "Sub-Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_groups/1 or /category_groups/1.json
  def destroy
    @category_group.destroy
    respond_to do |format|
      format.html { redirect_to request.referer , notice: "Category group was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_group
      @category_group = CategoryGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_group_params
      params.require(:category_group).permit(:name, :over_category_id)
    end
end

app/helpers/category_groups_helper.rb
module CategoryGroupsHelper
end

app/views/category_groups/_form.html.erb
<div class="w-screen flex items-center justify-center py-8 overflow-auto" >
    <div class="border rounded-lg border-gray-300 shadow-xl text-gray-900 bg-gray-200 w-6/12 max-h-max">
        <div class="max-w-7xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
            <div class="mt-5 md:mt-0 md:col-span-2">
                <%= form_with(model: category_group)  do |f|%>
                    <div class="shadow sm:rounded-md sm:overflow-hidden">
                        <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                            <div class="grid grid-cols-3 gap-6">
                                <div class="col-span-6 sm:col-span-3">
                                    <%= f.label t("Name"), class:"block text-sm font-medium text-gray-700 mb-5" %> 
                                    <%= f.text_field :name , class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-100 sec p-3 h-30  border border-gray-300 outline-none " %>
                                </div>
                            </div>
                        </div>
                        <%= f.number_field :over_category_id , class:"hidden", value:id %>
                        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <%= f.submit t("Save Sub-Category"), class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", data: {disable_with: "Validating ..."}%>
                        </div>
                    </div>
                <%end%>
            </div>
            <%= link_to t('Back'), request.referer, class:"mt-4 text-center flex w-20 justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
        </div>
    </div>
</div>

app/views/category_groups/edit.html.erb
<div class="flex justify-center" >
    <h1 class="mt-4 ml-4 text-xl" ><%= t("Edit Sub-Category") %></h1>
</div>

<%= render 'form', category_group: @category_group, id: @category_group.over_category_id  %>

app/views/category_groups/index.html.erb
<table>
  <tbody>
    <% @category_groups.each do |category_group| %>
      <tr>
        <td>
          <%= link_to category_group do %>
            <%= category_group.name %>
          <% end %>
        </td>
        <td><%= link_to 'Rename', edit_category_group_path(category_group) %></td>
        <td><%= link_to 'Delete', category_group, method: :delete, data: { confirm: "Deleteing this sub-category will delete all it's sub-categories, procede anyway ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_group_path %>

app/views/category_groups/new.html.erb
<div class="flex justify-center" >
    <h1 class="mt-4 ml-4 text-xl" ><%= t("New Sub-Category") %> </h1>
</div>

<%= render 'form', category_group: @category_group, id: params[:id] %>

app/views/category_groups/show.html.erb
<div class="my-5 pb-5 w-screen flex items-center justify-center min-h-max" >
  <div class="border rounded-lg border-gray-300 shadow-xl text-gray-900 bg-gray-200 max-w-max max-h-max">
    <div class="text-gray-900 bg-gray-200">
      <div class="p-4 flex justify-center">
          <h1 class="text-3xl">
            <%= t(@category_group.name) %> <%= t("Variants") %>
          </h1>
      </div>
      <div class="px-3 py-4 flex justify-center">
          <table class="w-96 text-md bg-white shadow-md rounded mb-4">
            <% @categories.each do |category| %>
              <tr class="border-b hover:bg-orange-100 bg-gray-100">
                <td class="p-3 px-5">
                  <%= link_to category_products_path(category), class:"bg-transparent" do %>
                    <%= t(category.title) %>
                  <% end %>
                </td>
                <td class="p-3 px-5 flex justify-end" >
                  <%= link_to t('Edit'), edit_category_path(category), class:"mr-3 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
                  <%= link_to t('Delete'), category, method: :delete, data: { confirm: "Deleteing this sub-category will delete all it's variants, proceed anyway ?" }, class:"text-sm bg-red-500 hover:bg-red-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
                </td>
              </tr>
            <% end %>
            <tr class="border-b hover:bg-orange-100 bg-gray-100">
              <td  colspan="2" class="p-3" >
                <%= link_to t('Add Variant'), new_variant_path(@category_group.id), class:"w-full text-center flex justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
              </td>
            </tr>
          </table>
      </div>
      <%= link_to t('Back'), OverCategory.find(@category_group.over_category_id), class:"mb-2 text-center flex w-20 justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </div>
</div>