config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :ratings
  resources :over_categories
  resources :category_groups
  root to: 'products#index'
  
  devise_for :users
  
  resources :messages
  resources :rooms
  resources :products
  resources :categories
  resources :categories, only: [:index] 
  resources :order_items, path: '/cart/items'


  get '/cart', to: 'order_items#index', as: 'payment_method'
  get 'rooms/:id',to: 'application#show'
  get 'categories/:id/products/new', to: 'products#new', as: 'new_category_product'
  get 'success', to: "checkout#success"
  get 'cancel', to: "checkout#cancel"
  get '/history', to: "transactions#index"
  get '/transactions', to: "transactions#admin_index", as: 'all_transactions'
  get '/transaction/:id/items', to: "transaction_items#index", as: 'transaction_items'
  get '/transaction/:id/details', to: "transaction_items#admin_index", as: 'admin_transaction_items'
  get '/invoice/:id', to: "transactions#invoice", as: "invoice"
  get '/categories/:id/products', to: "categories#index", as: 'category_products'
  get '/sub_category/new/:id', to: "category_groups#new", as: 'new_sub_category'
  get '/variant/new/:id', to: "categories#new", as: 'new_variant'
  get :search, controller: :products
  post 'checkout/create', to: "checkout#create"
  post 'delivery/create', to: "transactions#create", as: 'on_delivery'
  delete '/cart/clear', to: 'order_items#clear'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'
  delete '/categories/:id', to: 'categories#destroy', as: 'delete_category'

end

app/models/product.rb
class Product < ApplicationRecord

    validates :title, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0.01}
    validates :description, presence: true

    belongs_to :category
    has_one_attached :image, dependent: :destroy
    has_one_attached :ad, dependent: :destroy
    has_many :transaction_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    has_many :ratings, dependent: :destroy
    has_many :comments, dependent: :destroy
    include Rails.application.routes.url_helpers

    scope :filter_by_category, -> (category_id) {where category_id: category_id}
    scope :filter_by_rating, -> (rating) {where "rating >= ?",rating }
    scope :filter_by_min_price, -> (min_price) {where "price >= ?",min_price }
    scope :filter_by_max_price, -> (max_price) {where "price <= ?",max_price }

    def thumbnail 
        return self.image.variant(resize: '300x300!').processed
    end
    
    def image_url
        rails_blob_path(self.image, disposition: "attachment", only_path: true)
    end

    def ad_url
        rails_blob_path(self.ad, disposition: "attachment", only_path: true)
    end

    def show_thumbnail
        return self.image.variant(resize: '550x550!').processed 
    end

    def cart_thumbnail
        return self.image.variant(resize: '100x100!').processed   
    end


    def to_s
        title
    end
    
    after_create do 
        product = Stripe::Product.create(name: title , description: description, images: ["https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/32/7041/1.jpg?0874"])
        price = Stripe::Price.create(product: product, unit_amount: self.price.to_i*100, currency: "usd")
        update(stripe_product_id: product.id, stripe_price_id: price.id)
    end

    after_update :create_and_assign_new_stripe_price, if: :saved_change_to_price?
    def create_and_assign_new_stripe_price
        price = Stripe::Price.create(product: self.stripe_product_id, unit_amount: self.price.to_i*100, currency: "usd")
        update(stripe_price_id: price.id)
    end

    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, only: [:edit, :detroy, :update, :show]
    before_action :set_product, only: [:edit, :update, :show, :destroy]
        
    def index
        @pagy, @products = pagy(Product.all.order("created_at DESC"),items: 12)
    end

    def show
        @comment = Comment.new
        @rating = Rating.new
        @reviews = @product.ratings
        if @reviews.length == 0
            @avg_rating = 0
        else
            @avg_rating = @reviews.average(:score).round
        end
        @comments = Comment.where(product_id: @product.id).order("created_at DESC")
    end 

    def new 
        @product = Product.new
    end

    def search
        @pagy, @products = pagy(Product.ransack(title_cont: params[:q]).result(distinct: true),items: 12)
        prices=[]
        @products.each do |p|
            prices.push(p.price)
        end
        @min_price=prices.min
        @max_price=prices.max
        @pagy, @products = pagy(@products.filter_by_rating(params[:rating]), items: 12) if params[:rating].present?
        @pagy, @products = pagy(@products.filter_by_min_price(params[:min_price]), items: 12) if params[:min_price].present?
        @pagy, @products = pagy(@products.filter_by_max_price(params[:max_price]), items: 12) if params[:max_price].present?
        prices=[]
        @products.each do |p|
            prices.push(p.price)
        end
        @min_price_set=prices.min
        @max_price_set=prices.max
        respond_to do |format|
            format.html {}
            format.json {
                @products=@products.limit(5)
                puts(@products)
            }
        end
    
    end

    def edit 
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to root_path, notice: 'Product was successfully created'
        else
            redirect_to new_category_product_path
        end
    end

    def destroy
        @product.destroy
        redirect_to root_path, notice: "Product has been deleted successfully!"
    end

    def update
        if @product.update(params.require(:product).permit(:title, :image, :ad, :description, :price, :category_id, :show_ad))
            redirect_to @product, notice: 'Product was successfully updated'
        else
            render "edit" , alert: 'Product was not updated'
        end
    end

    private

    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:title, :image, :ad, :description, :price, :category_id, :show_ad)
    end

    def find_product
        @product = Product.find(params[:id])
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="max-w-7xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
    <div class="md:grid md:grid-cols-3 md:gap-6">
        <div class="md:col-span-1">
            <div class="px-4 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-gray-900"><%= t(type) %> <%= t("product") %></h3>
            </div>
        </div>
        <div class="mt-5 md:mt-0 md:col-span-2">
        <%= form_with model: @product, html: {multipart: true}  do |f|%>
                <div class="shadow sm:rounded-md sm:overflow-hidden">
                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                        <div class="grid grid-cols-3 gap-6">
                            <div class="col-span-6 sm:col-span-3">
                                <%= f.label t("Name"), class:"block text-sm font-medium text-gray-700" %> 
                                <%= f.text_field :title , class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-100 sec p-3 h-30  border border-gray-300 outline-none " %>

                            </div>
                        </div>

                        <div>
                            <label for="about" class="block text-sm font-medium text-gray-700 mb-2">
                                <%= t("Description") %>
                            </label>
                            <div class="mt-1">
                            <%= f.text_area :description , class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-100 sec p-3 h-30  border border-gray-300 outline-none"%>
                            </div>
                        </div>

                        <div>
                            <%=f.label :image, class:"block text-sm font-medium text-gray-700 mb-2"%>
                            <%= f.file_field :image %>
                        </div>

                        <div>
                            <%=f.label t("Ad image"), class:"inline text-sm font-medium text-gray-700 mb-2"%> <p class='inline text-xs text-gray-500 mb-2'>(<%= t("optional") %>)</p>
                            <%= f.file_field :ad, class: "block mt-2" %>
                        </div>

                        <div>
                            <%= t("Show this product in the slideshow") %>
                          <%= f.check_box :show_ad, {:class=>"mx-2"}, "true", "false" %>
                        </div>

                        <div>
                          <label class="block text-sm font-medium text-gray-700">
                            <%= t("Price") %>
                          </label>
                            <%= f.text_field :price, class:'mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-100 sec p-3 h-30  border border-gray-300 outline-none' %>
                        </div>


                        <div>
                            <%= f.text_field :category_id,value: params[:id], class:'hidden' %>
                        </div>

                    </div>
                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                      <%= f.submit t("Save Product"), class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", data: {disable_with: "Validating ..."}%>
                    </div>
                </div>
            <%end%>
        </div>
        <%= link_to t('Back'), request.referer, class:"text-center flex w-20 justify-center mx-2 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" %>
    </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product, type: t("Edit") %>

app/views/products/index.html.erb
<div class="flex flex-row">
    <div class="w-full">
        <%= render "shared/ads_slider", products: Product.all %>
        <div class=" flex flex-wrap grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-10 px-14">
            <% @products.each do |product| %>
                <div div class="post bg-transparent text-white pb-5 md:mb-6">
                    <div class=" shadow hover:shadow-lg transition duration-300 ease-in-out xl:mb-0 lg:mb-0 md:mb-0 mb-6 cursor-pointer group min-h-full">
                        <%= link_to product_path(product.id) do %>
                            <% if product.image.attached?%>
                                <%= image_tag product.thumbnail, class:"w-full transition duration-700 ease-in-out group-hover:opacity-60 " %>
                            <% end %>
                        <% end %>
                        <div class="px-4 py-3 bg-white">
                            <%= link_to product_path(product.id) do %>
                                <h1 class=" text-gray-800 font-semibold hover:text-blue-500 transition duration-300 ease-in-out"><%= truncate(product.title, :length => 29) %></h1>
                            <% end %>
                            <div class="flex py-2">
                                <p class="mr-2 text-xs text-gray-600"><%= number_to_currency product.price %></p>
                            </div>
                            <span class="flex items-center">
                                <% reviews = Rating.where(product_id: product.id) %>
                                <%avg_rating = 0 %>
                                <% if reviews.length > 0 %>
                                <% avg_rating = reviews.average(:score).round %>
                                <% end %>
                                <div class="flex pr-2">
                                <% (1..avg_rating).each do |i| %>
                                    <i class="focus:outline-none fas fa-star text-yellow-400 text-xs"  ></i>
                                <% end %>
                                <% ((avg_rating+1)..5).each do |i| %>
                                    <i class="focus:outline-none far fa-star text-gray-400 text-xs"  ></i>
                                <% end %>
                                </div>
                                <span class="pb-1 text-gray-600 ml-2"><%= pluralize( product.ratings.length, t('Reviews') ) %> </span>
                            </span>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>
<div class="flex justify-center items-center text-center pb-5"  >
    <%== pagy_nav(@pagy) %>
</div>

<style>
.pagy-nav {
    display: flex;
    --tw-space-x-reverse: 0;
    margin-right: calc(0.5rem * var(--tw-space-x-reverse));
    margin-left: calc(0.5rem * calc(1 - var(--tw-space-x-reverse)));
    padding-right: 20px;
    padding-top: 5px;
}
.pagy-nav .page a,
.pagy-nav .page.active,
.pagy-nav .page.prev.disabled,
.pagy-nav .page.next.disabled,
.pagy-nav-js .page a,
.pagy-nav-js .page.active,
.pagy-nav-js .page.prev.disabled,
.pagy-nav-js .page.next.disabled {
    display: block;
    border-radius: 0.5rem;
    padding-left: 0.75rem;
    padding-right: 0.75rem;
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
    font-size: 0.875rem;
    line-height: 1.25rem;
    --tw-text-opacity: 1;
    color: #1e78f7;
    font-weight: 600;
    --tw-bg-opacity: 1;
    background-color: rgba(229, 231, 235, var(--tw-bg-opacity));
    --tw-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
}
.pagy-nav .page a,
.pagy-nav .page.active,
.pagy-nav .page.prev.disabled,
.pagy-nav .page.next.disabled,
.pagy-nav-js .page a,
.pagy-nav-js .page.active,
.pagy-nav-js .page.prev.disabled,
.pagy-nav-js .page.next.disabled:hover{
    --tw-bg-opacity: 1;
    background-color: #1e78f7;
}
.pagy-nav .page a,
.pagy-nav .page.active,
.pagy-nav .page.prev.disabled,
.pagy-nav .page.next.disabled,
.pagy-nav-js .page a,
.pagy-nav-js .page.active,
.pagy-nav-js .page.prev.disabled,
.pagy-nav-js .page.next.disabled:active{
    --tw-bg-opacity: 1;
    background-color: #ffffff;
}

.pagy-nav .page.prev.disabled,
.pagy-nav .page.next.disabled {
    --tw-bg-opacity: 1;
    background-color: #8194ff;
    color:#ffffff;
    cursor: not-allowed;
  }
.pagy-nav .page.active,
.pagy-nav-js .page.active:active {
    --tw-bg-opacity: 1;
    background-color: #1e3ef7;
    --tw-text-opacity: 1;
    color: #ffffff;
}
</style>

app/views/products/new.html.erb
<%= render 'form', type: t("New") %>

app/views/products/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<section class="text-gray-700 body-font overflow-hidden bg-white">
  <div class="container px-5 py-10 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <% if @product.image.attached?%>
          <%= image_tag @product.show_thumbnail, class:"lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" %>
      <% end %>
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <div class="flex flex-row justify-between">
          <h2 class="text-sm title-font text-gray-500 tracking-widest"><%= t(Category.find(@product.category_id).title) %></h2>
          <div>
            <% if current_user && current_user.admin %>
              <%= link_to delete_product_path(@product), method: :delete, data: { confirm: "Are you sure?" }, class: "right-0 float-right inline mx-2" do %>
                <i style="font-size:24px" class="fa">&#xf014;</i>
              <% end %>
              <%= link_to edit_product_path(@product), class: "right-0 float-right inline" do %>
                <i class="fas fa-edit"></i>
              <% end %>
            <% end %>
            <div class="flex items-center pr-2">
              <div class="flex pr-2">
                <% (1..@avg_rating).each do |i| %>
                  <i class="focus:outline-none fas fa-star text-yellow-400 text-xs"  ></i>
                <% end %>
                <% ((@avg_rating+1)..5).each do |i| %>
                  <i class="focus:outline-none far fa-star text-gray-400 text-xs"  ></i>
                <% end %>
              </div>
              <span class="text-gray-600 ml-1"><%= pluralize( @reviews.length, t('Reviews') ) %> </span>
            </div>
          </div>
        </div>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-1"><%= @product.title %></h1>
        <div class="flex mb-4">
        </div>
        <p class="leading-relaxed"><%= @product.description %></p>
        <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
          <div class="flex">
          </div>
          <div class="flex ml-6 items-center">
            <span class="flex items-center">
              <span class="text-gray-600 mr-2"><%= t("Your Rating") %> : </span>
              <% if current_user %>
                <% ratings = Rating.where(user_id: current_user.id ,product_id: @product.id) %>
                <%= form_with(model: @rating) do |form| %>  
                  <div class="flex cursor-pointer">
                    <div class="">
                      <% if ratings.length > 0 %>
                        <% score = ratings[0].score %>
                        <% (1..ratings[0].score).each do |i| %>
                          <button type="submit" class="focus:outline-none	 fas fa-star text-yellow-400 text-xs" data-star="<%= i %>" data-product="<%= @product.id %>" id="<%= "rating-star-#{i}-#{@product.id}"%>" ></button>
                        <% end %>
                        <% ((ratings[0].score+1)..5).each do |i| %>
                          <button type="submit" class="focus:outline-none far fa-star text-gray-400 text-xs" data-star="<%= i %>" data-product="<%= @product.id %>" id="<%= "rating-star-#{i}-#{@product.id}"%>" ></button>
                        <% end %>
                      <% else %>
                        <% score = 0 %>
                        <% (1..5).each do |i| %>
                            <button type="submit" class="focus:outline-none	far fa-star text-gray-400 text-xs" data-star="<%= i %>" data-product="<%= @product.id %>" id="<%= "rating-star-#{i}-#{@product.id}"%>" ></button>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="hidden">
                    <%= form.number_field :score,value:score ,id:"score-#{@product.id}",class:"text-gray-900" %>
                  </div>
                  <div class="hidden">
                    <%= form.text_field :user_id,value:current_user.id  %>
                  </div>
                  <div class="hidden">
                    <%= form.text_field :product_id,value:@product.id %>
                  </div>
                  <div class="hidden">
                    <%= form.submit %>
                  </div>
                <% end %>
              <% else %>
                <%= form_with(model: @rating) do |form| %>  
                  <div class="hidden">
                    <%= form.number_field :score,value:0 ,id:"score-#{@product.id}",class:"text-gray-900" %>
                  </div>
                  <div class="hidden">
                    <%= form.text_field :user_id,value:0  %>
                  </div>
                  <div class="hidden">
                    <%= form.text_field :product_id,value:@product.id %>
                  </div>
                  <div class="flex cursor-pointer">
                    <div class="">
                      <% (1..5).each do |i| %>
                          <button type="submit" class="focus:outline-none	far fa-star text-gray-400 text-xs" data-star="<%= i %>" data-product="<%= @product.id %>" id="<%= "rating-star-#{i}-#{@product.id}"%>" ></button>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </span>
          </div>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900"><%= number_to_currency @product.price %></span>
          <%= form_tag order_items_path, remote: true, class:"flex max-h-10 h-10" do %>
            <%= hidden_field_tag :product_id, @product.id %>
            <%= number_field_tag :quantity, 1, min: 1, class: "mx-3 max-w-20 w-20 inline-block text-center bg-gray-200 hover:bg-gray-300 border-1 focus:outline-none", id: "cart-number-field-show" %>
            <button type="submit" class="mx-3 flex ml-auto text-white bg-blue-500 border-0 py-2 px-4 focus:outline-none hover:bg-blue-600 rounded" @click="showModal2 = true">
              <%= t("Add to cart") %>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if current_user %>
    <div class="max-w-4xl py-1 xl:px-5 flex justify-center mb-8 mx-auto">
      <div class="w-11/12 mt-2 md:mt-0 ">
        <%= form_with(model: @comment,class: "relative h-auto py-10 overflow-hidden bg-gray-100 border-b-2 border-gray-300 rounded-lg shadow-2xl px-7") do |form| %>
          <h3 class="mb-6 text-2xl font-medium text-center"><%= t("Write a comment") %></h3>

          <div class="field">
            <%= form.text_area :content,class:"w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none",placeholder:t("Your comment"), rows:"3", cols:"33" %>
          </div>

          <div class="hidden">
            <%= form.text_field :user_id, value: current_user.id %>
          </div>

          <div class="hidden">
            <%= form.text_field :product_id, value: @product.id %>
          </div>
          <div class="flex float-right">
            <input type="submit" value=<%= t("Submit comment") %> name="submit" class="text-white px-4 py-3 bg-blue-500 rounded-lg">
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% if @comments.length > 0 %>
    <% @comments.each do |comment| %>
      <div class="px-10 pb-2 pt-1 my-0 bg-white w-11/12 animation-fade animation-delay mx-auto sm:px-12 xl:px-5">
        <div class="flex items-center w-full px-6 py-2 mx-auto mt-3 bg-gray-100 border border-gray-200 rounded-lg sm:px-8 md:px-12 sm:py-8 sm:shadow lg:w-5/6 xl:w-2/3">
          <a href="#" class="flex items-center mt-2 mb-2 mr-6">
            <% if User.find(comment.user_id).avatar.attached? %>
              <%= image_tag User.find(comment.user_id).image_url, class:"hidden object-cover w-14 h-14 mx-4 rounded-full sm:block" %>
            <% else %>
              <div class="flex items-center justify-center h-10 w-10 rounded-full bg-indigo-500 flex-shrink-0" >
                <%= User.find(comment.user_id).name[0].capitalize %>
              </div>
            <% end %>
          </a>
          <div>
            <h3 class="text-lg font-bold text-blue-500 sm:text-xl md:text-2xl"><%= User.find(comment.user_id).name %></h3>
            <p class="text-sm font-bold text-gray-300"><%= comment.created_at %></p>
            <p class="mt-2 text-base text-gray-600 sm:text-lg md:text-normal">
              <%= comment.content %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<!--comments component-->
</section>

<body x-data="{ showModal1: false, showModal2: false, showModal3: false }" :class="{'overflow-y-hidden': showModal1 || showModal2 || showModal3}">
  <div
    class="fixed inset-0 w-full h-full z-20 bg-black bg-opacity-50 duration-300 overflow-y-auto"
    x-show="showModal2"
    x-transition:enter="transition duration-300"
    x-transition:enter-start="opacity-0"
    x-transition:enter-end="opacity-100"
    x-transition:leave="transition duration-300"
    x-transition:leave-start="opacity-100"
    x-transition:leave-end="opacity-0"
  >
    <div class="relative inset-y-40 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-2 sm:mx-auto my-10 opacity-100">
      <div
        class="relative bg-white shadow-lg rounded-lg text-gray-900"
        @click.away="showModal2 = false"
        x-show="showModal2"
        x-transition:enter="transition transform duration-300"
        x-transition:enter-start="scale-0"
        x-transition:enter-end="scale-100"
        x-transition:leave="transition transform duration-300"
        x-transition:leave-start="scale-100"
        x-transition:leave-end="scale-0"
      >
        <header class=" flex flex-col justify-center items-center p-3 text-blue-600">
          <div class="flex justify-center w-28 h-28 border-4 border-blue-600 rounded-full mb-4">
            <svg class="fill-current w-20" viewBox="0 0 20 20">
              <path
                d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z"
              ></path>
            </svg>
          </div>
          <h2 class="font-semibold text-2xl"><%= t("Success") %></h2>
        </header>
        <main class="p-3 text-center">
          <p>
            <div>
              <div class="inline" id="added-product-confirm-alert-<%= current_cart.order.token %>" ></div>
              <div class="inline" ><%= t("has been added to your cart") %>.</div>
            </div>          </p>
        </main>
        <footer class="flex justify-center bg-transparent">
          <button
            class="bg-blue-600 font-semibold text-white py-3 w-full rounded-b-md hover:bg-blue-700 focus:outline-none focus:ring shadow-lg hover:shadow-none transition-all duration-300"
            @click="showModal2 = false"
          >
          <%= t("Confirm") %>
          </button>
        </footer>
      </div>
    </div>
  </div>
</body>
<script>
  var stars = document.getElementsByClassName("fa-star");
  var rating = 0;
  set_star = function(data_star,data_product){
    for (var j=1;j<=5;j++ ){
      if(j<=data_star){
        star = document.getElementById(`rating-star-${j}-${data_product}`);
      star.classList.remove("text-gray-400");
      star.classList.remove("far");
      star.classList.add("text-yellow-400");
      star.classList.add("fas");
      }else{
        star = document.getElementById(`rating-star-${j}-${data_product}`);
        star.classList.add("text-gray-400");
        star.classList.add("far");
        star.classList.remove("text-yellow-400");
        star.classList.remove("fas");
      }
    }
      
  };
  select_star = function(){
    var data_star=this.getAttribute("data-star");
    var data_product=this.getAttribute("data-product");
    set_star(data_star,data_product);
    
  };
  select_rating = function(){
    var data_star=this.getAttribute("data-star");
    var data_product=this.getAttribute("data-product");
    set_star(data_star,data_product);
    rating = data_star;
    var score = document.getElementById(`score-${data_product}`);
    score.value = rating;
  };
  undo_rating = function(){
    var data_product=this.getAttribute("data-product");
    var score = document.getElementById(`score-${data_product}`);
    rating = score.value;
    var data_star=rating;
    set_star(data_star,data_product);

  };
    

  for (var i = 0; i < stars.length; i++) {
    stars[i].addEventListener('click', select_star, false);
    stars[i].addEventListener('click', select_rating, false);
    stars[i].addEventListener('mouseenter', select_star, false);
    stars[i].addEventListener('mouseleave', undo_rating, false);
  };
  
</script>